"""Builds wordpress-block.html from index.html.

The output is a single snippet to paste into a WordPress "Custom HTML" block.
Every style is scoped under .smm-lp so the landing page and your theme don't
restyle each other, the page's own nav bar is dropped (your theme has its own
header), and fonts load from Google Fonts instead of the repo's assets folder.

Run from this folder after editing index.html:
    python3 build-wordpress.py
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
SCOPE = ".smm-lp"
FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
    '<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,700'
    '&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">\n'
)


def scope_selector(sel):
    sel = sel.strip()
    if sel in (":root", "body", "html"):
        return SCOPE
    if sel == "*":
        return f"{SCOPE}, {SCOPE} *"
    return f"{SCOPE} {sel}"


def scope_rules(css):
    """Prefix every selector in a flat list of rules (no nested at-rules)."""
    out = []
    for m in re.finditer(r"([^{}]+)\{([^{}]*)\}", css):
        selectors, body = m.group(1).strip(), m.group(2)
        if selectors.startswith("@font-face"):
            continue  # fonts come from Google Fonts instead
        scoped = ", ".join(scope_selector(s) for s in selectors.split(","))
        out.append(f"{scoped} {{{body}}}")
    return "\n".join(out)


def scope_css(css):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out, i = [], 0
    for m in re.finditer(r"@media[^{]+\{((?:[^{}]*\{[^{}]*\})*)\s*\}", css):
        out.append(scope_rules(css[i:m.start()]))
        out.append(m.group(0)[: m.group(0).index("{") + 1] + "\n" + scope_rules(m.group(1)) + "\n}")
        i = m.end()
    out.append(scope_rules(css[i:]))
    return "\n".join(out)


src = (HERE / "index.html").read_text()
css = src[src.index("<style>") + 7 : src.index("</style>")]
ld = re.search(r'<script type="application/ld\+json">.*?</script>', src, re.S).group(0)
body = src[src.index("<body>") + 6 : src.index("</body>")]
body = re.sub(r'<nav class="nav".*?</nav>\s*', "", body, flags=re.S)

# Drop the scroll-behavior rule on html (it would affect the whole WordPress site)
# and make the wrapper break out of the theme's content column to full width.
scoped = scope_css(css).replace("html { scroll-behavior: smooth; }", "")
scoped += (
    f"\n{SCOPE} {{ width: 100vw; position: relative; left: 50%; right: 50%;"
    " margin-left: -50vw; margin-right: -50vw; overflow-x: hidden; }"
    f"\n{SCOPE} h1, {SCOPE} h2, {SCOPE} h3 {{ margin-top: 0; text-transform: none; color: inherit;"
    " font-family: \"Fraunces\", Georgia, serif; letter-spacing: -0.01em; }"
    f"\n{SCOPE} ul, {SCOPE} ol {{ list-style: none; }}"
    f"\n{SCOPE} .faq summary, {SCOPE} .card, {SCOPE} .feature p {{ font-family: \"Inter\", system-ui, sans-serif; }}"
    f"\n{SCOPE} a {{ text-decoration: none; box-shadow: none; }}"
    f"\n{SCOPE} .btn, {SCOPE} .btn:hover, {SCOPE} .btn:visited {{ color: #fff; }}"
    f"\n{SCOPE} .btn-ghost, {SCOPE} .btn-ghost:hover, {SCOPE} .btn-ghost:visited {{ color: var(--ink); }}"
)

# The nav no longer exists, so remove the lines that reference it.
body = body.replace('  const nav = document.getElementById("nav");\n', "")
body = body.replace('    nav.classList.toggle("scrolled", y > 8);\n', "")

snippet = (
    "<!-- SMM Dashboard landing page. Generated by build-wordpress.py from index.html. -->\n"
    + FONTS
    + ld
    + "\n<style>\n"
    + scoped
    + "\n</style>\n"
    + f'<div class="{SCOPE[1:]}">\n'
    + body.strip()
    + "\n</div>\n"
)
(HERE / "wordpress-block.html").write_text(snippet)
print(f"Wrote wordpress-block.html ({len(snippet):,} bytes)")
